  name: GemCommonsKit
  options:
    bundleIdPrefix: de.gematik.ti.common
    deploymentTarget:
      macOS: 11.0
      iOS: 12.1
  settings:
    base:
      CODE_SIGN_IDENTITY: ""
      SWIFT_VERSION: 5.0
      ALWAYS_SEARCH_USER_PATHS: NO
      FRAMEWORK_SEARCH_PATHS: "$(inherited)"
      BUILD_LIBRARY_FOR_DISTRIBUTION: YES
    configs:
      Release:
        SWIFT_COMPILATION_MODE: wholemodule
      Debug:
        SWIFT_COMPILATION_MODE: incremental
  packages:
    Nimble:
      url: https://github.com/Quick/Nimble
      majorVersion: 10.0.0
  targets:
    GemCommonsKit:
      type: framework
      platform: [iOS, macOS]
      info:
        path: Resources/GemCommonsKit_Info.plist
      sources:
        - Sources/GemCommonsKit
      scheme:
        testTargets:
          - GemCommonsKitTests_${platform}
        gatherCoverageData: true
    ObjCCommonsKit:
      type: framework
      platform: [iOS, macOS]
      sources:
        - Sources/ObjCCommonsKit
      info:
        path: Resources/ObjCCommonsKit_Info.plist
      scheme:
        gatherCoverageData: true
    GemCommonsKitTests:
      type: bundle.unit-test
      settings:
        base:
          BUILD_LIBRARY_FOR_DISTRIBUTION: NO
      platform: [iOS, macOS]
      sources:
        - path: Tests
      dependencies:
        - package: Nimble
        - target: GemCommonsKit_${platform}
  buildImplicitDependencies: true
